import json
import sys

# This script reads service rules from a file generated by the ServiceRules.py
# Creates a file called rules.txt and nd
import tarfile

with open('service_rules.json', 'r') as json_file:
    json_load = json.load(json_file)
# print(json_load['web']['languages']['id'])
original_stdout = sys.stdout
with open('rules.txt', 'w') as r:
    sys.stdout = r
    data = json_load['included']

    for x in data:
        if (x['provider'] == "gcp" or x['provider'] == 'aws'):
            print("Rule ID: ", x['id'], "\n", "Rule Title: ", x['title'], "\n", "Rule Category: ", x['categories'], "\n",
              "Cloud Provider: ", x['provider'], "\n\n")

sys.stdout = original_stdout

print

