# coding: utf-8

"""
    Trend Micro Deep Security API

    Copyright 2018 - 2022 Trend Micro Incorporated.<br/>Get protected, stay secured, and keep informed with Trend Micro Deep Security's new RESTful API. Access system data and manage security configurations to automate your security workflows and integrate Deep Security into your CI/CD pipeline.  # noqa: E501

    OpenAPI spec version: 20.0.686
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from deepsecurity.models.connector_migration_task import ConnectorMigrationTask  # noqa: F401,E501
from deepsecurity.models.connector_unable_to_move import ConnectorUnableToMove  # noqa: F401,E501


class BatchConnectorMigrationTaskList(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'connector_migration_tasks': 'list[ConnectorMigrationTask]',
        'connectors_unable_to_migrate': 'list[ConnectorUnableToMove]'
    }

    attribute_map = {
        'connector_migration_tasks': 'connectorMigrationTasks',
        'connectors_unable_to_migrate': 'connectorsUnableToMigrate'
    }

    def __init__(self, connector_migration_tasks=None, connectors_unable_to_migrate=None):  # noqa: E501
        """BatchConnectorMigrationTaskList - a model defined in Swagger"""  # noqa: E501

        self._connector_migration_tasks = None
        self._connectors_unable_to_migrate = None
        self.discriminator = None

        if connector_migration_tasks is not None:
            self.connector_migration_tasks = connector_migration_tasks
        if connectors_unable_to_migrate is not None:
            self.connectors_unable_to_migrate = connectors_unable_to_migrate

    @property
    def connector_migration_tasks(self):
        """Gets the connector_migration_tasks of this BatchConnectorMigrationTaskList.  # noqa: E501

        ConnectorMigrationTask created.  # noqa: E501

        :return: The connector_migration_tasks of this BatchConnectorMigrationTaskList.  # noqa: E501
        :rtype: list[ConnectorMigrationTask]
        """
        return self._connector_migration_tasks

    @connector_migration_tasks.setter
    def connector_migration_tasks(self, connector_migration_tasks):
        """Sets the connector_migration_tasks of this BatchConnectorMigrationTaskList.

        ConnectorMigrationTask created.  # noqa: E501

        :param connector_migration_tasks: The connector_migration_tasks of this BatchConnectorMigrationTaskList.  # noqa: E501
        :type: list[ConnectorMigrationTask]
        """

        self._connector_migration_tasks = connector_migration_tasks

    @property
    def connectors_unable_to_migrate(self):
        """Gets the connectors_unable_to_migrate of this BatchConnectorMigrationTaskList.  # noqa: E501

        Connectors that cannot be migrated.  # noqa: E501

        :return: The connectors_unable_to_migrate of this BatchConnectorMigrationTaskList.  # noqa: E501
        :rtype: list[ConnectorUnableToMove]
        """
        return self._connectors_unable_to_migrate

    @connectors_unable_to_migrate.setter
    def connectors_unable_to_migrate(self, connectors_unable_to_migrate):
        """Sets the connectors_unable_to_migrate of this BatchConnectorMigrationTaskList.

        Connectors that cannot be migrated.  # noqa: E501

        :param connectors_unable_to_migrate: The connectors_unable_to_migrate of this BatchConnectorMigrationTaskList.  # noqa: E501
        :type: list[ConnectorUnableToMove]
        """

        self._connectors_unable_to_migrate = connectors_unable_to_migrate

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BatchConnectorMigrationTaskList, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BatchConnectorMigrationTaskList):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other

